"""Niche seeds for automated catalog builds — combines fixed lists and generated combos."""

from __future__ import annotations

# Core launch niches (hand-picked).
LAUNCH_EXTRA_NICHES = [
    "Bluetooth Speakers",
    "Wireless Earbuds",
    "Smart Watches",
    "Tablet Accessories",
    "Camera Accessories",
    "Drone Accessories",
    "LED Strip Lights",
    "Office Chairs",
    "Standing Desks",
    "Desk Organizers",
    "Wall Art",
    "Throw Pillows",
    "Area Rugs",
    "Kitchen Knives",
    "Air Fryer Accessories",
    "Baking Supplies",
    "Water Bottles",
    "Protein Shakers",
    "Resistance Bands",
    "Dumbbells",
    "Exercise Bikes",
    "Treadmill Accessories",
    "Running Shoes",
    "Athletic Socks",
    "Compression Sleeves",
    "Tennis Equipment",
    "Golf Accessories",
    "Soccer Gear",
    "Basketball Accessories",
    "Swimming Goggles",
    "Surfing Gear",
    "Snowboard Accessories",
    "Ski Goggles",
    "Motorcycle Accessories",
    "Bike Lights",
    "Bike Helmets",
    "RV Accessories",
    "Boat Accessories",
    "Garden Tools",
    "Planters",
    "Grill Accessories",
    "Patio Furniture",
    "Hammocks",
    "Coolers",
    "Tents",
    "Sleeping Bags",
    "Camping Stoves",
    "Flashlights",
    "Power Banks",
    "Phone Chargers",
    "Laptop Bags",
    "Backpacks",
    "Travel Accessories",
    "Luggage",
    "Passport Holders",
    "Baby Strollers",
    "Baby Monitors",
    "Diaper Bags",
    "Nursing Pillows",
    "Dog Beds",
    "Dog Toys",
    "Cat Trees",
    "Aquarium Supplies",
    "Bird Cages",
    "Makeup Brushes",
    "Nail Art",
    "Beard Grooming",
    "Electric Toothbrushes",
    "Massage Guns",
    "Essential Oil Diffusers",
    "Candles",
    "Craft Supplies",
    "Sewing Accessories",
    "Party Supplies",
    "Halloween Decorations",
    "Christmas Decorations",
    "Wedding Accessories",
    "Musical Instruments",
    "Guitar Accessories",
    "Piano Accessories",
    "Art Supplies",
    "Board Games",
    "Puzzle Games",
    "RC Cars",
    "Model Kits",
    "Collectible Figures",
    "Vintage Clothing",
    "Handbags",
    "Belts",
    "Scarves",
    "Hats",
    "Work Boots",
    "Safety Glasses",
    "Tool Sets",
    "Power Drill Accessories",
    "Storage Bins",
    "Garage Organization",
    "Cleaning Supplies",
    "Robot Vacuums",
    "Air Purifiers",
    "Humidifiers",
    "Space Heaters",
    "Electric Blankets",
    "Mattress Toppers",
    "Weighted Blankets",
    "Pillows",
    "Shower Curtains",
    "Bath Mats",
    "Towel Sets",
]

_NICHE_MODIFIERS = (
    "Wireless",
    "Portable",
    "Electric",
    "Smart",
    "Mini",
    "Professional",
    "Outdoor",
    "Indoor",
    "Travel",
    "Kids",
    "Baby",
    "Pet",
    "Car",
    "Home",
    "Kitchen",
    "Office",
    "Gaming",
    "Fitness",
    "Yoga",
    "Camping",
)

_NICHE_PRODUCTS = (
    "Accessories",
    "Supplies",
    "Equipment",
    "Tools",
    "Organizers",
    "Storage",
    "Lights",
    "Chargers",
    "Cases",
    "Covers",
    "Bags",
    "Bottles",
    "Mats",
    "Chairs",
    "Desks",
    "Shelves",
    "Decor",
    "Toys",
    "Grooming",
    "Safety",
    "Monitors",
    "Cameras",
    "Speakers",
    "Headphones",
    "Watches",
    "Gloves",
    "Masks",
    "Filters",
    "Brushes",
    "Kits",
)

_CATEGORY_ROOTS = (
    "Dog",
    "Cat",
    "Baby",
    "Kitchen",
    "Bathroom",
    "Bedroom",
    "Living Room",
    "Garage",
    "Garden",
    "Patio",
    "Office",
    "Gym",
    "Sports",
    "Fishing",
    "Hunting",
    "Cycling",
    "Running",
    "Swimming",
    "Golf",
    "Tennis",
    "Soccer",
    "Basketball",
    "Baseball",
    "Skincare",
    "Hair",
    "Makeup",
    "Nail",
    "Jewelry",
    "Watch",
    "Phone",
    "Laptop",
    "Tablet",
    "Camera",
    "Drone",
    "RV",
    "Boat",
    "Motorcycle",
    "Truck",
    "Car",
    "Wedding",
    "Party",
    "Craft",
    "Art",
    "Music",
    "Guitar",
    "Piano",
    "RC",
    "Collectible",
)


def _generated_combo_niches() -> list[str]:
    out: list[str] = []
    for mod in _NICHE_MODIFIERS:
        for product in _NICHE_PRODUCTS:
            out.append(f"{mod} {product}")
    for root in _CATEGORY_ROOTS:
        out.append(f"{root} Supplies")
        out.append(f"{root} Accessories")
        out.append(f"{root} Equipment")
    return out


def all_catalog_seed_niches(*, include_initial_36: list[str] | None = None) -> list[str]:
    """Deduped niche list for seeding the catalog build queue."""
    seen: set[str] = set()
    ordered: list[str] = []
    sources = list(include_initial_36 or []) + LAUNCH_EXTRA_NICHES + _generated_combo_niches()
    for niche in sources:
        key = " ".join((niche or "").strip().split()).lower()
        if len(key) < 3 or key in seen:
            continue
        seen.add(key)
        ordered.append(" ".join((niche or "").strip().split()))
    return ordered
